build_profile := env_var_or_default('BOULDER_PROFILE', 'local-x86_64')
build_file := join(invocation_directory(), "stone.yaml")
local_repo := env_var_or_default('LOCAL_REPO', '${HOME}/.cache/local_repo/x86_64')

pkgs_file := join(invocation_directory(), "pkglist")
cache_dir := join(invocation_directory(), "moss_cache")
blit_dir := join(invocation_directory(), "root")

default: build

# Prepare the ephemeral root + storage for kernel work
_prepare_root:
    #!/usr/bin/env bash
    set -euxo pipefail
    if [[ ! -d "{{cache_dir}}" ]]; then
        mkdir "{{cache_dir}}"
        moss -D {{cache_dir}} repo add volatile "https://packages.serpentos.com/volatile/x86_64/stone.index"
    else
        moss -D {{cache_dir}} repo update
    fi
    if [[ -d "{{blit_dir}}" ]]; then
        sudo rm -rf "{{blit_dir}}"
    fi
    mkdir "{{blit_dir}}"
    moss -D "{{cache_dir}}" install --to="{{blit_dir}}" $(cat {{pkgs_file}}) --yes-all

# Enter nspawn environment for kernel updates
nspawn: _prepare_root
    sudo systemd-nspawn -D "{{blit_dir}}" --bind=$(pwd):/kernel --chdir=/kernel


# Build the stone.yml recipe using boulder
_build target:
    cd {{ invocation_directory() }}; boulder build -u {{ if path_exists(target) == "true" { target } else { error("Missing stone.yml file") } }} -p {{ build_profile }}

# Build stone.yml from the current directory
build: (_build build_file)

# create LOCAL_REPO dir if it doesn't exist
create-local:
    #!/usr/bin/env bash
    set -euo pipefail
    if [[ ! -d {{local_repo}} ]]; then
       mkdir -pv {{local_repo}}
    fi

# index .stones in LOCAL_REPO (create it if it doesn't exist)
index-local: create-local
    cd {{ invocation_directory() }} && moss index {{local_repo}}

# list .stones in LOCAL_REPO (create it if it doesn't exist)
ls-local: create-local
    cd {{ invocation_directory() }} && ls -AFcghlot {{local_repo}}

# move .stones to LOCAL_REPO (create if it doesn't exist) and reindex it
mv-local: create-local
    cd {{ invocation_directory() }} && mv -v *.stone {{local_repo}}/ && moss index {{local_repo}}
